org: romayneeastmond
app: aws-sites
service: aws-sites
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MONGODB_URI: ${param:MONGODB_URI}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi: "*"
  graphql:
    handler: handler-apollo.handler
    events:
      - http:
          path: graphql
          method: post
          cors: false
  sites-dev-add:
    handler: src/dev/sites-dev-addSite.handler
    events:
      - httpApi:
          path: /sites/add
          method: post
  sites-dev-delete:
    handler: src/dev/sites-dev-deleteSite.handler
    events:
      - httpApi:
          path: /sites/delete
          method: delete
  sites-dev-get:
    handler: src/dev/sites-dev-getSite.handler
    events:
      - httpApi:
          path: /sites/get
          method: get
  sites-dev-list:
    handler: src/dev/sites-dev-listSites.handler
    events:
      - httpApi:
          path: /sites/list
          method: get
  sites-dev-update:
    handler: src/dev/sites-dev-updateSite.handler
    events:
      - httpApi:
          path: /sites/update
          method: put
